version: "3.9"
services:
    postgres:
        image: postgres:latest
        container_name: meetingtable-db
        hostname: postgres
        ports:
            - "5432:5432"
        env_file:
            .env

    backend:
        build: .
        container_name: meetingtable-backend
        ports:
            - "3000:3000"
        env_file:
            - .env
        depends_on:
            - postgres
volumes:
    meeting_table_data:
