version: "3.9"
services:
    postgres:
        image: postgres:latest
        container_name: test-db
        hostname: postgres
        ports:
            - "5432:5432"
        environment:
            POSTGRES_USER: DB_USER
            POSTGRES_PASSWORD: DB_PASSWORD
            POSTGRES_DB: test
volumes:
    test_data:
